# 예외

* ArithmeticException
  * 정수를 0으로 나눌 때
* NullPointerException
  * null 레퍼런스를 참조할 때
* ClassCastException
  * 변활할 수 없는 타입으로 객체를 변환할 때
* OutOfMenoryError
  * 메모리가 부족한 경우 발생
* ArrayIndexOutOfBoundsException
  * 배열의 범위를 벗어난 접근 시
* IllegalArgumentException
  * 잘못된 인자 전달 시 발생
* IOException
  * 입출력 동작 실패 또는 인터럽트 시
* NumberFormatException
  * 문자열이 나타내는 숫자와 일치하지 않는 타입의 숫자로 변환 시
* InputMismatchException
  * Scanner 클래스의 nextInt()를 호출하였지만, 사용자가 'a' 등과 같이 문자를 입력한 경우
* 다 외울필요 없이 자동완성으로 생성 가능

* 예시

  ```java
  try {
  	System.out.println(dividend+"를 "+divisor+"로 나누면 몫은"+ dividend/divisor+"입니다.");
  }catch(NullPointerException e){
  	System.out.println("NullPointerException 대응하기");
  	e.printStackTrace();	// 예외 종류 출력
  	System.out.println(e.getMessage());	// 예외메세지 출력
  }catch(ClassCastException e){
  	System.out.println("ClassCastException 대응하기");
  	e.printStackTrace();
  	System.out.println(e.getMessage());
  }catch(ArithmeticException e){
  	System.out.println("ArithmeticException 대응하기");
  	e.printStackTrace();
  	System.out.println(e.getMessage());
  }catch(Exception e){
  	System.out.println("나머지 모든 Exception 대응하기");
  	e.printStackTrace();
  	System.out.println(e.getMessage());
  }finally{
  	System.out.println("Exception 발생 유무와 상관없이 무조건 실행됨.");
  }
  System.out.println("중요한 작업...");// try catch 구문을 사용하므로서 중요한 작업 출력 가능
  ```
